### PR TITLE
updated dependency of ParseUI and removed deprecated refreshInBackgroundWithBlock

### PR DESCRIPTION
**Pull request by tzapu**

### CODE REVIEW

**Comment by eneko** [comment]
What is the reasoning behind making ParseUI a dependency?

**Comment by tzapu** [comment]
Hi, PFImageView is in ParseUI now. If you just add the pod as is, it will error on compile.

**Comment by tzapu** [comment]
as described here https://github.com/hathway/Parse-PromiseKit/issues/3

**Comment by Killectro** [comment]
Thanks for submitting this, I hadn't had a chance to get to it yet. Merging.

**Pull request merged**
